SELECT "YEAR", (AREA_FIPS || '-' || OWN_CODE) AS CODE, AREA_TITLE, OWN_TITLE, INDUSTRY_TITLE, AGGLVL_TITLE,

(SELECT OTY_ANNUAL_AVG_EMPLVL_CHG FROM STG_QCEW subquery WHERE 
subquery.YEAR = '2015' AND
subquery.YEAR = STG_QCEW.YEAR AND
subquery.AREA_FIPS = STG_QCEW.AREA_FIPS  AND 
subquery.OWN_CODE = STG_QCEW.OWN_CODE AND
subquery.AREA_TITLE = STG_QCEW.AREA_TITLE AND
subquery.OWN_TITLE = STG_QCEW.OWN_TITLE AND
subquery.INDUSTRY_TITLE = STG_QCEW.INDUSTRY_TITLE AND
subquery.AGGLVL_TITLE = STG_QCEW.AGGLVL_TITLE
) 
AS "2015"

FROM STG_QCEW 
GROUP BY "YEAR", CODE, AREA_TITLE, OWN_TITLE, INDUSTRY_TITLE, AGGLVL_TITLE, "2015" 
ORDER BY "YEAR", CODE, AREA_TITLE, OWN_TITLE, INDUSTRY_TITLE, AGGLVL_TITLE, "2015"


SELECT "YEAR", (AREA_FIPS || '-' || OWN_CODE) AS CODE, AREA_TITLE, OWN_TITLE, INDUSTRY_TITLE, AGGLVL_TITLE
FROM STG_QCEW WHERE "YEAR" = '2015'
ORDER BY "YEAR", CODE, AREA_TITLE, OWN_TITLE, INDUSTRY_TITLE, AGGLVL_TITLE

SELECT * FROM STG_REGIONALPURCHASINGPOWER where RPP = 'RPP'
