SELECT DISTINCT state_name, state_abbreviation from lkp_city_fips order by state_name
/*STG_AGGCOMPANYLOCATIONS.LIST_NAME, 
STG_AGGCOMPANYLOCATIONS.STORE_NAME, 
STG_AGGCOMPANYLOCATIONS.COUNTY, 
LKP_CITY_FIPS.STATE_COUNTY_FIPS, 
LKP_FIPS_COORDINATES.COUNTY_FIPS*/
FROM STG_AGGCOMPANYLOCATIONS WHERE LENGTH("STATE") > 2 ORDER BY "STATE"
--JOIN LKP_CITY_FIPS ON COUNTY OR CITY AND STATE OR CITY AND STATE ABBREVIATION
LEFT JOIN LKP_CITY_FIPS ON 
(UPPER(STG_AGGCOMPANYLOCATIONS.COUNTY) = LKP_CITY_FIPS.COUNTY_NAME OR 
LKP_CITY_FIPS.CITY_NAME = UPPER(STG_AGGCOMPANYLOCATIONS.CITY)) --AND 
--(LKP_CITY_FIPS.STATE_NAME = UPPER(STG_AGGCOMPANYLOCATIONS.STATE) or 
--LKP_CITY_FIPS.STATE_ABBREVIATION = UPPER(STG_AGGCOMPANYLOCATIONS.STATE))
--JOIN LKP_FIPS_COORDINATES ON LONGITUDE AND LATITUDE
LEFT JOIN LKP_FIPS_COORDINATES ON STG_AGGCOMPANYLOCATIONS.LATITUDE = LKP_FIPS_COORDINATES.LATITUDE AND 
STG_AGGCOMPANYLOCATIONS.LONGITUDE = LKP_FIPS_COORDINATES.LONGITUDE
WHERE LKP_CITY_FIPS.STATE_COUNTY_FIPS IS NULL AND LKP_FIPS_COORDINATES.COUNTY_FIPS IS NULL


SELECT STG_AGGCOMPANYLOCATIONS.LIST_NAME, 
STG_AGGCOMPANYLOCATIONS.STORE_NAME, 
STG_AGGCOMPANYLOCATIONS.COUNTY, 
LKP_CITY_FIPS.STATE_COUNTY_FIPS 
FROM STG_AGGCOMPANYLOCATIONS
LEFT JOIN LKP_CITY_FIPS ON 
(UPPER(STG_AGGCOMPANYLOCATIONS.COUNTY) = LKP_CITY_FIPS.COUNTY_NAME) OR 
(LKP_CITY_FIPS.CITY_NAME = UPPER(STG_AGGCOMPANYLOCATIONS.CITY))
SELECT STG_AGGCOMPANYLOCATIONS  `

SELECT COUNT(*) FROM STG_AGGCOMPANYLOCATIONS WHERE COUNTY IS NULL AND LATITUDE IS NULL AND LONGITUDE IS NULL

SELECT STG_AGGCOMPANYLOCATIONS.TICKER, 
STG_AGGCOMPANYLOCATIONS.LIST_NAME, 
STG_AGGCOMPANYLOCATIONS.STORE_NAME, 
STG_AGGCOMPANYLOCATIONS.COUNTY 

FROM STG_AGGCOMPANYLOCATIONS limit 500

select * from sessions

SELECT CLOSE_ALL_SESSIONS()

select * from (select '' as catalog_name, schema_name, table_name, column_name, case when sql_datetime_sub = 10 then 1111 else data_type end as data_type, data_type_name, column_size, buffer_length, decimal_digits, num_prec_radix, nullable, remarks, column_default as column_def, sql_type_id as sql_data_type, sql_datetime_sub, char_octet_length, ordinal_position, is_nullable, case is_identity when 't' then 'YES' when 'f' then 'NO' else null end as is_autoincrement, 0 as user_data_type from v_catalog.odbc_columns order by catalog_name, schema_name, table_name, ordinal_position) as vmd where COLUMN_NAME ilike '%' escape E'\\' and TABLE_NAME ilike 'sessions' escape E'\\' and SCHEMA_NAME ilike 'd68eb234fff8f2750cbf7dd02b20fd0e' escape E'\\' 

fA7ErkPjKeD3PrYS

select count(*) from stg_glassdoorsalary

select * from stg_qcew limit 20

\set MaxNodeID `vsql -t -c 'SELECT MAX(node_id) AS MaxNodeID FROM v_catalog.nodes;'
\echo :MaxNodeID


Select * from lkp_city_fips limit 10

${FIPS||02068||String||where}$

select * from lkp_city_fips where state_county_fips=${FIPS||'02068'||||where}$

SELECT --COUNT(*)
--/*
STG_COWEBSITELOCATIONS.JUST_CITY_NAME, 
STG_COWEBSITELOCATIONS.JUST_STATE_ABBREV, 
LKP_CITY_FIPS.CITY_NAME, 
LKP_CITY_FIPS.STATE_ABBREVIATION, 
LKP_CITY_FIPS.STATE_COUNTY_FIPS
--*/ 
FROM STG_COWEBSITELOCATIONS
LEFT JOIN LKP_CITY_FIPS ON (STG_COWEBSITELOCATIONS.JUST_CITY_NAME = LKP_CITY_FIPS.CITY_NAME
OR STG_COWEBSITELOCATIONS.JUST_COUNTY_NAME = LKP_CITY_FIPS.COUNTY_NAME
)
AND
STG_COWEBSITELOCATIONS.JUST_STATE_ABBREV = LKP_CITY_FIPS.STATE_ABBREVIATION WHERE 
LKP_CITY_FIPS.STATE_COUNTY_FIPS IS NULL AND (STG_COWEBSITELOCATIONS.CITY IS NOT NULL AND 
STG_COWEBSITELOCATIONS.STATE IS NOT NULL) AND STG_COWEBSITELOCATIONS.JUST_CITY_NAME LIKE '%HANOVER%'


select * from lkp_city_fips where CITY_NAME LIKE '%HANOVER%' AND STATE_ABBREVIATION = 'MD'
MANHATTAN

SELECT DISTINCT MGOC, GOC  FROM STG_GLASSDOORSALARY ORDER BY MGOC, GOC

select count(cASE_NUMBER) FROM STG_ENIGMAH1BVISA

SELECT COUNT(*)
--COMPANYTICKER, LINKEDINCOMPANYNAME, LINKEDINCOMPANYID, JOBLOCATION, JOBPOSTINGDATE, JOBTITLE, JOBURL, JOBCITY, JOBSTATEABBREV, JOBSTATENAME 
FROM STG_LINKEDINJOBPOSTINGS where companyticker = 'WMT'

select CLOSE_ALL_SESSIONS()